use specified color_ for EndEffector marker
Addresses this clang warning

<<<
moveit_visual_tools/include/moveit_visual_tools/imarker_end_effector.h:150:29: error: private field 'color_' is not used [-Werror,-Wunused-private-field]
  rviz_visual_tools::colors color_ = rviz_visual_tools::PURPLE;
                            ^
1 error generated.
>>>

We could have removed the member just as well (it barely matters...),
but that would entail an unnecessary API change in the constructor.

I added the default value for the constructor parameter as it is always overwritten until now...